spring:
  datasource:
    url: jdbc:mysql://localhost:3306/student_tracker
    username: springstudent
    password: springstudent

  # Turn off the spring boot banner
  main:
    banner-mode: off

# Reduce logging level. Set logging level to warn
logging:
  level:
    root: warn
